server:
  port: 8080
spring:
  rabbitmq:
    #host: 47.98.108.122
    #username: LinWood_David
    port: 5672
    host: 192.168.159.133
    username: David
    password: 123456
    virtual-host: /
    listener:
      direct:
        #开启ack
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
    #开启发送确认
    publisher-confirms: true
    #开启发送失败退回
    publisher-returns: true

#启用RabbitMQ运行状况检查。
management:
  health:
    rabbit:
      enabled: true